openapi: 3.1.0

info:
  title: ChatGpt Plugin Github Search Repositories Api
  version: 1.0.0
  description: Api specification for ChatGpt Plugin Github Search Repositories Api

paths:
  /search:
    get:
      summary: Search Github Repositories using a query
      operationId: searchGithub
      tags:
        - github
      parameter:
        - in: query
          name: q
          required: true
          description: Query to search GitHub Repositories
          schema:
            type: string

      responses:
        '200':
          description: Successfull response
          content:
            application/json:
              schema:
                type: object
                properties:
                  repos:
                    type: array
                    items:
                      $ref: '#/components/schemas/Repository'

components:
  schemas:
    Repository:
      type: object
      properties:
        name:
          type: string
        stars:
          type: integer
        url:
          type: string
        description:
          type: string
      required:
        - name
        - stars
        - url
        - description
